# 
#Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

                      East         West         North            South
|________________|_____________|_____________|______________|______________|
|     Males      |     50      |     142     |     131      |     70       |
|     Females    |     550     |     351     |     480      |     350      |


In [ ]:
#steps
#H0 : all prop. are similar
#H1 :at least one is different
#we will use chi square test.

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [3]:
Q3 = pd.read_csv('BuyerRatio.csv')
print(Q3)

  Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750


In [9]:
# converting in to a array
ar = np.array([[50,142,131,70],[435,1523,1356,750]])
print(ar)

[[  50  142  131   70]
 [ 435 1523 1356  750]]


In [10]:
#Chi square test
stats.chi2_contingency(ar)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [ ]:
#p value 0.660>0.05, thus we cannot reject null hypothesis. i.e all the proportions are equal
#male - female buyer rations are similar across the regions.