In [ ]:
#TeleCall uses 4 centers around the globe to process customer order forms.
#They audit a certain %  of the customer order forms. 
#Any error in order form renders it defective and has to be reworked before processing.
#The manager wants to check whether the defective %  varies by centre.
#Please analyze the data at 5% significance level and help the manager draw appropriate inferences

In [ ]:
#steps :
#H0 : variable are independent i.e defective % does not varies by centre.
#H1 : not all are equal i.e defective % varies by centre.
# use chi square test to determine.

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [3]:
Q4 = pd.read_csv('CostomerOrderForm.csv')
print(Q4)

    Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]


In [6]:
# we nedd to get the count for each columns for error free and defective.
errorfree = []
defective = []

for i in range(0,4):
    a,b = Q4.iloc[:,i].value_counts()
    errorfree.append(a) 
    defective.append(b)
print(errorfree)
print(defective)

[271, 267, 269, 280]
[29, 33, 31, 20]


In [8]:
#converting into array.
ar = np.array([errorfree, defective])
print(ar)

[[271 267 269 280]
 [ 29  33  31  20]]


In [9]:
#carrying out chi square test.
stats.chi2_contingency(ar)
#p value 0.277 is greater than 0.05 alpha. so we cannot reject null hypothesis. 
#i.e. defective % do not vary by centers.

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))